//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperBotModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadWords
    {
        public int Id { get; set; }
        public string badWord { get; set; }
        public int idStore { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
