//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperBotModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuration()
        {
            this.serviceInterval = 15;
            this.expirationTime = 2;
        }
    
        public int serviceInterval { get; set; }
        public int expirationTime { get; set; }
        public string priceRegex { get; set; }
        public int idConfiguration { get; set; }
    }
}
