//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScraperBotModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public string title { get; set; }
        public Nullable<decimal> originalPrice { get; set; }
        public Nullable<decimal> salePrice { get; set; }
        public int idStore { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
